### ISSUE TITLE
Toolbar appears in the middle when selecting character on the edge 

### ISSUE THREAD

**Issue by kozhuhds** [globocom/megadraft#111]
Toolbar appears in the middle when selecting character on the edge http://take.ms/kPJDf

**Comment by marcelometal** [comment]
Hi @kozhuhds, For me the selection works fine in Firefox and does not work in Chrome.  What browser you are using?

**Comment by kozhuhds** [comment]
hi, @marcelometal, I use Chrome. yeah it works properly in FF.

**Comment by makeitrein** [comment]
Probably related to this... https://github.com/facebook/draft-js/pull/876
