### ISSUE TITLE
How to render display options correctly?

### ISSUE THREAD

**Issue by hiepthai** [globocom/megadraft#118]
The display options of plugin seem not to work? Am I missing something?

Should I override the `blockStyleFn` of the Editor?

**Comment by marcelometal** [comment]
Hi @hiepthai,

You should not override the blockStyleFn... Did you create your plugin with Megadraft generator? 

The `src/plugin.js` seems this: 

```js
import {MegadraftIcons} from "megadraft";

export default {
  type: constants.PLUGIN_TYPE,
  buttonComponent: Button,
  blockComponent: Block,
  options: {
    defaultDisplay: "medium",
    displayOptions: [
      {"key": "small", "icon": MegadraftIcons.MediaSmallIcon, "label": "SMALL"},
      {"key": "medium", "icon": MegadraftIcons.MediaMediumIcon, "label": "MEDIUM"},
      {"key": "big", "icon": MegadraftIcons.MediaBigIcon, "label": "BIG"}
    ]
  }
};
```

For example, in `src/Block.js` you can access the `options` this way: 
`this.props.blockProps.plugin.options;`

I know, we need some documentation about it.

If you have any doubts please let me know.

**Comment by hiepthai** [comment]
I found the way to access block options data with `this.props.data.display`. I can handle selected option and render it correctly now.

The demo and document also need to have some lines about this.

**Comment by StuartFeldt** [comment]
Is this handled by #150?

**Comment by ricobl** [comment]
Sure it is! Thanks @StuartFeldt!
