### ISSUE TITLE
Problem rendering a custom Toolbar

### ISSUE THREAD

**Issue by tizzle** [globocom/megadraft#119]
I'm using Megadraft 0.4.9 from NPM and ran into an issue trying to render a custom toolbar. I tried it as suggested in the Docs:

This is how i define the toolbar
```
import React, {Component} from "react";

export default class CustomToolbar extends Component {

    constructor(props) {
        super(props);
    }

    render() {
        return (
            <div>
                Custom Toolbar
            </div>
        );
    }
}

```

This is how a pass it to Megadraft:

```
<MegadraftEditor
    editorState={this.state.editorState}
    onChange={this.onChange}
    Toolbar={CustomToolbar}
/>
```

But the custom toolbar i imported is not rendered, instead i get the default toolbar.
Can you help me with this?

Thanks!

**Comment by vierno** [comment]
Hello, @tizzle, how are you importing your customToolbar, if you insert a breakpoint, is your toolbar being used as a prop to MegadraftEditor? I've had a similar issue when I was doing a wrong import.

**Comment by tizzle** [comment]
Hey @vierno,

thanks for getting back!

Unfortunately i let go of the idea to use a customized toolbar and did some incredibly hacky css to frankenstein the default toolbar. That's why i can't try out your suggestion right now.
I'm pretty sure i imported the toolbar like this:

```
import CustomToolbar from './default-toolbar' 
```

The contents of default-toolbar.jsx are the first codeblock in my original post.

If you're not sure straightaway that this cannot work, i will do a minimal example and report back.

Thanks for your time!

**Comment by vierno** [comment]
Hello @tizzle , I couldn't reproduce this problem, I did a copy and paste of your code into our example ant it worked fine... If you could set an example it will surely help us.

**Comment by vierno** [comment]
Closing due inactivity
