### ISSUE TITLE
Possible to add customStyleMap property for MegadraftEditor?

### ISSUE THREAD

**Issue by makeitrein** [globocom/megadraft#123]
Hey globocom - many thx for a great draft-js implementation... making my boss a very happy camper right now. I'd like to add the customStyleMap property to the PluginsEditor, as such...

` <Editor customStyleMap={this.props.customStyleMap} ...`

so I can implement my own customStyleMap (below)...
`const styleMap = {
    red: {
        color: 'rgb(235, 20, 76)',
    },
    orange: {
        color: 'rgb(255, 105, 0)',
    },
    yellow: {
        color: 'rgb(252, 185, 0)',
    },
    highlight: {
        background: '#ffeb3b',
        padding: "2px 4px"
    },
    green: {
        color: 'rgb(0, 208, 132)',
    },
    blue: {
        color: 'rgb(6, 147, 227)',
    },
    pink: {
        color: 'rgb(247, 141, 167)',
    },
    purple: {
        color: 'rgb(153, 0, 239)',
    },
};`

Open to a PR for this?

**Comment by vierno** [comment]
Hello @makeitrein I think it would be a nice addition to Megadraft, you can make a PR =)

**Comment by vierno** [comment]
Issue was solved by #126
