### ISSUE TITLE
Need help to create a "text alignment" functionality

### ISSUE THREAD

**Issue by mdarcemont** [globocom/megadraft#131]
Hi,

I want to add a the ability to align the text in the editor.

With vanilla draft-js, here is what I would do : 

1) Add elements in the block render map
```
const blockRenderMap = Immutable.Map({
  'align-center': {
    element: 'div'
  }
});
const extendedBlockRenderMap = DefaultDraftBlockRenderMap.merge(blockRenderMap);
```
and pass it to the editor
`blockRenderMap={extendedBlockRenderMap}`

2) Write a custom "blockStyleFn"
```
function getBlockStyle(contentBlock) {
  const type = contentBlock.getType();

  switch (type) {
    case 'align-center':
      return 'align-center';
 ...
```

But Megadraft prevent the overriding of blockStyleFn. I can only override the blockRenderMap.

So, how could I do this ? With the plugins, I guess ? But I don't want the sidebar, I want a classic button in the toolbar, like the "blockquote" button. 

Thank you for your help !

**Comment by mdarcemont** [comment]
Hi,

I've made something on my fork :
https://github.com/mdarcemont/megadraft/commit/f4b0ed9d3614789e8265224853d50dca7ceda7b1

Basically, you just have to provide an array that contains the new block definitions : 
```
const blockStyles = [
  {type: "align-left", element: "div", className: "block-align-left"},
  {type: "align-center", element: "div", className: "block-align-center"},
  {type: "align-right", element: "div", className: "block-align-right"}
];
```
and pass it to the editor :
`blockStyles={blockStyles}`

Then this array is used to generate the blockStylesFn and the blockRenderMap.

I don't know if it suits to your vision of Megadraft, so I don't make a pull request for now. If you like it, I'll write the tests...

**Comment by vierno** [comment]
Hello, @mdarcemont ,

I think it would be a nice feature to have, feel free to open a PR.

**Comment by grex84** [comment]
Anyone figure out a way to create a text alignment functionality. @mdarcemont I tried your method but it doesn't seem to be working for me.

**Comment by CameronAckermanSEL** [comment]
@grex84 it seems to only work on his fork, did you try that?

**Comment by grex84** [comment]
i have, but is there any way to apply this to a parent div? This method seems to replace the header tag, if one has been applied to the same block.
