### ISSUE TITLE
Link Button doesn't work

### ISSUE THREAD

**Issue by sevikon** [globocom/megadraft#133]
Hi guys, 
it seems that from version 0.4.14 it's impossible to create link with link button.
Probably current state is undefined.

![bug_stack_2](https://cloud.githubusercontent.com/assets/6122467/23505957/2043f2da-ff46-11e6-8ff0-bcd6cabc668e.png)

![bug_stack](https://cloud.githubusercontent.com/assets/6122467/23505958/205d2dea-ff46-11e6-88ae-85dddf49e4cd.png)

For 0.4.13 everything works fine.
Are you using latest version on your demo website?

**Comment by marcelometal** [comment]
Hi @sevikon, for each commit in master, the demo website is updated.

Please, could you use the latest version of Megadraft, 0.4.16?

Cheers!

**Comment by sevikon** [comment]
Hi @marcelometal 
I tested it. The same problem. 
It could be caused by draft-js@0.10.0, because 0.4.13 version uses draft-js@0.9.1 and I don't get any exception.
I thought that is global problem. But if you running latest version on demo and it works I can you use previous version. No problem :) You can close issue.

**Comment by marcelometal** [comment]
ok! if there is any problem please let me know.

Thank you.
