### ISSUE TITLE
Lists are nuts

### ISSUE THREAD

**Issue by gaku-sei** [globocom/megadraft#134]
There are several problem with lists and soft returns.

1 It's impossible to perform more than one soft return per list item
2 Once a soft return has been done, it's impossible to soft return in a list item anymore
3 Once the bugs above have been triggered, to type "up" from a bottom list item will move the cursor to a random list item above

![megadraft](https://cloud.githubusercontent.com/assets/3982371/23516855/b5aceaac-ff6e-11e6-8540-07db54e918e2.gif)
Every return are soft in the video

**Comment by vierno** [comment]
Hello @gaku-sei,

Points 1 and 2 are the desired behavior that we wanted for Megadraft, we ensure that no double soft-return can be made on the text blocks as they have no semantic meaning. We could have the option to disable this behavior if it's needed. We are always open for pull requests.

For point 3, I believe that it is how draft-js works, the navigation "jumps" over some empty blocks, I could see that happening on other editors.

**Comment by gaku-sei** [comment]
@vierno thank you for your answer.

Thanks for your explanations on points 1 and 2, the problem is I need to be able to perform n soft-returns for the tool I'm working on, so, is there any way to change this behaviour (ideally, without forking the whole project) ?

I forgot to mention the fact that soft-returns are not possible at all in some list items (you may notice it in the video).

For point 3 I am not sure draft-js ignores empty blocks, or it just does for some of them, which would be weird. On the video the blocks containing soft-returns are ignored, but not the other ones, which is pretty odd.

**Comment by vierno** [comment]
Currently there is no way to prevent this behavior, we could have this as a Editor component option.

The arrow navigation is not handled by Megadraft, we need to look at draft-js to see if there's something we could do about the it.

**Comment by cameacke** [comment]
This would be a pretty simple fix yes? Just need to change
https://github.com/globocom/megadraft/blob/master/src/components/MegadraftEditor.js
` handleReturn={this.handleReturn}`
to
`handleReturn={this.props.handleReturn || this.handleReturn}`

**Comment by vierno** [comment]
Hello @cameackeSEL,

I made the change you proposed and released it, you can check it on v0.4.18.
