### ISSUE TITLE
Strange behaviour when changing image size

### ISSUE THREAD

**Issue by pex** [globocom/megadraft#138]
I am using the standard image plugin from examples.
When changing image dimensions, surrounding blocks adapt a really strange behaviour when editing (see video).

### How to Reproduce:

1. Go to [megadraft.io](http://megadraft.io/)
2. Change dimensions of attached image
3. Start editing the block above
4. Press `Enter`
5. Continue editing the same block
6. The newly created block magically fills up with content of the above block

![megadraft-image-state-bug](https://cloud.githubusercontent.com/assets/60568/23700739/22374224-03f4-11e7-8f25-85a387621dbb.gif)

**Comment by marcelometal** [comment]
Hi @pex, thanks for reporting.

We can confirm that this a bug, we will try to fix it as soon as we can, but in the meantime feel free to submit a pull-request if you are in a hurry, we will be glad to review your code.

**Comment by mateuspontes** [comment]
@ricobl @vierno @marcelometal I need some help on how to test this behaviour.

**Comment by marcelometal** [comment]
Fixed in #155
