### ISSUE TITLE
resetStyleNewLine prop not working

### ISSUE THREAD

**Issue by farzinshams** [globocom/megadraft#139]
I'm not sure if I understood the purpose of this prop correctly, but shouldn't a newline reset the style on the next paragraph?

![screen shot 2017-03-08 at 11 58 59 am](https://cloud.githubusercontent.com/assets/8161916/23709005/badb3678-03f6-11e7-8e86-d6218551593d.png)

**Comment by petry** [comment]
Hi @farzinshams ,

Megadraft only resets the style when you create a new blank paragraph, if you split a sentence in two, Megadraft will mantain the style.

Maybe we need to make this point clear on Docs!

**Comment by ricobl** [comment]
Hey @farzinshams!

As @petry mentioned, the style will only be reset when the cursor is at the end of the line. Is that your case?

Can you reproduce the problem on our [demo website](http://megadraft.io/#/?_k=izo8e3)? It worked for me.

Can you post a snippet of your code so we can investigate a little bit further?

**Comment by farzinshams** [comment]
@ricobl @petry I didn't split the sentence in two. My actions were as follows: 1) Write 'first paragraph with style', 2) Select text and change it to bold, 3) Hit enter, 4) Write 'next paragraph, still with style'. 

Interestingly, I couldn't reproduce the problem in your demo website, but I could reproduce it in a cloned example provided in https://github.com/globocom/megadraft#developing

On the demo website:
![screen shot 2017-03-10 at 2 56 49 pm](https://cloud.githubusercontent.com/assets/8161916/23806778/d33f105c-05a1-11e7-9bae-78d06d4c081a.png)

Cloned:
![screen shot 2017-03-10 at 2 57 41 pm](https://cloud.githubusercontent.com/assets/8161916/23806801/eceeecfc-05a1-11e7-9857-cb0f617dfb2f.png)

**Comment by vierno** [comment]
Hello @farzinshams,
Is your clone update with megadraft's master? This is a new feature introduced recently.
If it is update, could you check the value of the resetStyleNewLine prop locally?

**Comment by marcelometal** [comment]
@farzinshams, did you see the [documentation](http://megadraft.io/#/docs/customization?_k=vou968)? You should set this prop to `true`, default is `false`.

**Comment by farzinshams** [comment]
@vierno Sorry, my bad, it wasn't up to date with master.
