### ISSUE TITLE
Need to opt out of MediaWrapper managing readonly state of editor

### ISSUE THREAD

**Issue by cameackeSEL** [globocom/megadraft#140]
Request Type: 
Feature (but kind of a bug) 

Expected: 
If I have a plugin/custom block type that manages readonly state of the parent editor (per Draft JS recommended practice), Megadraft components will not interfere with my control of readonly.

Actual: 
MediaWrapper will set editor readonly to true onFocus and false onBlur. This means if the user clicks on or interacts with a component that cannot be bound events (like some divs), MediaWrapper will set the editor state back to readonly false with its onBlur event.

Recommendations:
Need an elegant way of doing one of the following:

1. Suppressing MediaWrapper onBlur and onFocus events with some sort of flag
2. Opting out of MediaWrapper wrapping the plugin entirely

This is kind of tricky because it raises a question about how the API should work. We could also do 
3. Allow user to specify custom blockProps to pass to MediaWrapper. 

Ideas are welcome, and I'm happy to make a PR for this.

**Comment by cameackeSEL** [comment]
Worked with @rocobl, he recommended that I use stopPropagation to resolve the issue.

I put these on my container elements

`onFocus={e => e.stopPropagation()}
onBlur={e => e.stopPropagation()}`

and it prevented media wrapper from calling its focus and blur methods.

**Comment by ricobl** [comment]
Awesome @cameackeSEL, I'm glad that it worked!
