### ISSUE TITLE
Integrate Megadraft with draft-js-plugins

### ISSUE THREAD

**Issue by vierno** [globocom/megadraft#141]
We would like to use plugins from [draft-js-plugins](https://github.com/draft-js-plugins/draft-js-plugins) on Megadraft Editor.

One of the ways to do this is to move parts of Megadraft to a draft-js-plugin. Also, we need to give Megadraft plugins a new name, we could call those `atomicBlocks`.

We will continue exporting `MegadraftEditor` as a component. To do so, all the editor methods and utils need to be ported to plugins' format. Megadraft usage should be like that:

```js
import {MegadraftEditor} from Megadraft;

class MyEditor extends Component {
  ...
  render() {
    return <MegadraftEditor
            plugins={[...]}
            atomicBlocks={[...]} />
  }
}
```

Progress:

* [x] rename every "plugin" reference to "atomicBlock"
* [x] use `draft-js-plugins` as the main `Editor` component
* [x] port custom `Megadraft` features to a plugin or multiple plugins
* [x] make sure tests are passing
* [x] decide between stable / beta draft-js-plugins (we'll go for the beta)
* [ ] add support for `getInitialReadOnly` and `setInitialReadOnly`
* [ ] make built-in `atomicBlocks` use `setEditorState` instead of `onChange`
* [ ] write a plugins migration plan
* [ ] release intermediary version with warnings on deprecated props when possible
* [ ] remove warnings
* [ ] release new version (1.0?)

**Comment by StevenIseki** [comment]
Hey @vierno I have done some work on this over in the following repo https://github.com/vacenz/megadraft-js-plugins 

These new plugins are modified mainly from draft-js-plugins and aim to emulate the toolbar and sidebar from Megadraft as well as adding gif, embed, emoji picker and color plugins.

My thoughts are that this could be a basis for a new major version of Megadraft using Draft-js-plugins and including the plugins to be published in this repo.

Last Draft which was my experimental project could become obsolete, as there isn't much point in both of them being so similar.

Just a note, this repo is experimental at this stage and if you want to go in another direction, I can use them for a new major version of Last Draft and will rename the repo to last-draft-js-plugins

Thanks, let me know your thoughts and hopefully we can tweak this repo and get the plugins published and usable in a future version of Megadraft.

**Comment by ricobl** [comment]
Hi @StevenIseki, thanks for giving a shot at this and sorry for the long delay...

I think we want to go in a different direction. We need to support the current Megadraft plugin system or at least make the transition smooth for our users.

Some work was done in the [draftjs-plugins-integration](https://github.com/globocom/megadraft/tree/draftjs-plugins-integration) branch but it's not complete, some features are broken and a lot of automated tests are failing.

**Comment by StuartFeldt** [comment]
Is there a roadmap available (even if sparse) for how integration with draft-js-plugins is progressing? Or a high level overview of how this integration will be handled, if at all?

**Comment by ricobl** [comment]
Hey @StuartFeldt!

Even though this is a very desirable feature, there's no official schedule. I added a rough description of the required steps and the current status.

Please let us know if this helps!

**Comment by sibelius** [comment]
what is the status of this?
