### ISSUE TITLE
megadraft leads to 'Server-side React render was discarded. Make sure that your initial render does not contain any client-side code.'

### ISSUE THREAD

**Issue by geng890518** [globocom/megadraft#144]
![image](https://cloud.githubusercontent.com/assets/19452264/23944146/c9d25600-09ac-11e7-9fdf-62137b452cfe.png)
 anyone met this problem?

**Comment by cameackeSEL** [comment]
Could you provide a code snippet that reproduces the issue?

**Comment by vierno** [comment]
Hello @geng890518, what are the versions of Megadraft and React that you are using?

**Comment by geng890518** [comment]
@vierno My React version is 15.4.2 and my Megadraft version is 0.4.19,thanks!

**Comment by geng890518** [comment]
@cameackeSEL I'm learnintg to use it. It's my codes.

import React, { Component } from 'react';
// import ReactDOM from 'react-dom';
import {MegadraftEditor, editorStateToJSON, editorStateFromRaw} from 'megadraft';

export default class editor extends Component {
  constructor(props) {
    super(props);
    this.state = {
      editorState: editorStateFromRaw(null),
      cliennt: false
    };
    this.onChange = ::this.onChange;
    this.onsubmit = () => {this._onsubmit();};
  }
 onChange(editorState) {
   this.setState({editorState});
 }
 _onsubmit() {
   const {editorState} = this.state;
   const content = editorStateToJSON(editorState);
   console.log(content);
 }
  render() {
    // const styles = require('./editor.scss');
    require('../../../node_modules/megadraft/dist/css/megadraft.css');
    return (
      <div>
        <MegadraftEditor
        placeholder="begin your journey"
        editorState={this.state.editorState}
        onChange={this.onChange} />
        <button onClick={this.onsubmit}>提交</button>
      </div>
    );
  }
}

**Comment by cameackeSEL** [comment]
The only thing that really jumps out at me is the require for the css in the render(). Can you move that to the top of the page and see what happens?

**Comment by geng890518** [comment]
@cameackeSEL Cool! It's OK now ,Thanks!
