### ISSUE TITLE
Question : Can we use this library if we work with HTML

### ISSUE THREAD

**Issue by remy-poirier** [globocom/megadraft#147]
Hello,

I'm looking for a good draftjs component to integrate into my project and Megadraft seems to be the ultimate solution. For now I was using the one on the DraftJS website, which is cool, but miss some features.

Just to explain, in my application, I let the user choose if in it's description he wants to type pure HTML (via a specific HTML editor), or if he wants to type its content in "simple mode" (via your draftjs plugin)

The thing is that in DB I only store HTML, not JSON, so I want to know if I can use your library to let the user type its content, then get the EditorState and convert it to HTML to save in DB, and when I load the news, I want to load the HTML and convert it to a content state that I will pass to the your editor. 

Can I do that with your library ? I mean I'm surely gonna need some import/export lib, but will the HTML be what I saw in the Editor ?

**Comment by ricobl** [comment]
Hi @remy-poirier!

It's certainly possible but Megadraft doesn't have this functionality built-in, you will probably do this conversion on your own.

There are libraries that can help you with this, here is a good place to start your search:

https://github.com/nikgraf/awesome-draft-js#common-utilities

I'm closing the issue ok? Feel free to comment if you need more info!

Also, you can try asking for help on DraftJS' Slack team:

https://draftjs.herokuapp.com/

**Comment by kunokdev** [comment]
Would be great if you actually added example for this somewhere
