### ISSUE TITLE
Deleting newline deletes the component above

### ISSUE THREAD

**Issue by chachra** [globocom/megadraft#149]
See for example https://www.evernote.com/l/AAUG4GtrbOdNBr8RKnqX7bQ6OCECfWGJxw0 - where the "+" icon is it deletes the component  with testing word in it above. It should simple delete the line and if delete is pressed again then delete the above component.

Let me know if I am thinking wrong. Thanks!

**Comment by ricobl** [comment]
Hey @chachra! This behavior is currently handled by DraftJS, it's not customized by Megadraft.

I wouldn't call this "wrong" but it is somehow desired, if the line gets removed it would be impossible to insert content between those blocks as we don't have drag-and-drop yet.

**Comment by chachra** [comment]
Hmm ok.... I'd have thought a "+" would insert content into any gap. This to my other issue replied to, I feel like what is your thought on a "document" being 100's of blocks of content / editors/  images/plugins etc. ? That way lines are only problem with WYSIWYG, but a document is more than text, its images, folders, external app references (github, google docs, youtube) etc.

Megadraft seems mature for sure, but am unsure on who will win in this space (tough to predict!!) :-) Plugin architecture is key for sure, but also data management, storage and real-time/sockets base updating of state. Slate for example is using https://facebook.github.io/immutable-js/

**Comment by ricobl** [comment]
Hi @chachra!

I'm not sure I got your question, maybe you can join us on our (Slack channel)[https://draftjs.herokuapp.com/] to continue this discussion.

I'm closing the issue ok?
