### ISSUE TITLE
editor not showing after importing  megadraft.css file

### ISSUE THREAD

**Issue by chsisodiya** [globocom/megadraft#160]
Editor not getting displayed after  importing megadraft.css. Under react tab in developer tool I can see all the tools are present but are invisible and right aligned.

**Comment by ricobl** [comment]
Hey @chsisodiya!

Did you follow the [usage documentation](http://megadraft.io/#/docs/overview)?

There's probably something wrong with your setup, do you have it somewhere public?

**Comment by chsisodiya** [comment]
yeah I followed it. Without including the megadraft.css file  editor is shown but properly formatted. 
After including css file editor just disappeared. I will post the code soon.

**Comment by chsisodiya** [comment]
I used the same code.. as mentioned in the document..below is snippet..

import React from "react";
import ReactDOM from "react-dom";
import {MegadraftEditor, editorStateFromRaw} from "megadraft";

**require('megadraft/dist/css/megadraft.css');**

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {editorState: editorStateFromRaw(null)};
    **this.onChange = this.onChange.bind(this);**
  }

  onChange(editorState) {
    this.setState({editorState});
  }

  render() {
    return (
      <MegadraftEditor
        editorState={this.state.editorState}
        onChange={this.onChange}/>
    )
  }
}

ReactDOM.render(
  <App />,
  document.getElementById('container')
);

**Comment by ricobl** [comment]
Looks like there are a few things missing in your code. You forgot to return something on `App.render` and forgot to pass your App to `ReactDOM.render`.

I'm closing the issue ok? Feel free to ask for help on our Slack channel. Register [here](https://draftjs.herokuapp.com/) and join us [here](https://draftjs.slack.com/messages/megadraft/).

Anyway, here is a modified version that should work:

```js
import React from "react";
import ReactDOM from "react-dom";
import {MegadraftEditor, editorStateFromRaw} from "megadraft";

require('megadraft/dist/css/megadraft.css');

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {editorState: editorStateFromRaw(null)};
    this.onChange = this.onChange.bind(this);
  }

  onChange(editorState) {
    this.setState({editorState});
  }

  render() {
    // You should return something here...
    return (
      <MegadraftEditor editorState={this.state.editorState} />
    )
  }
}

// You should pass something to render
ReactDOM.render(<App />, document.getElementById('container'));
```
