### ISSUE TITLE
Jumping Toolbar

### ISSUE THREAD

**Issue by sevikon** [globocom/megadraft#161]
![image](https://user-images.githubusercontent.com/6122467/27154779-9ecbb004-5156-11e7-8a99-f978f2c4f0ec.png)
Hi guys,
it seems to be problem with toolbar when I click outside editor container (on FF and Chrome).
How to reproduce it (on FF, ver. 53.0.3): 
1) Select some text -> toolbar is displayed
2) Click outside container
3) Toolbar jumps to random position

How to reproduce it (on Chrome, ver. 59.0.3071.86): 
1) Select some text
2) Click bold or other button
3) Click outside container (toolbar is still displayed)
4) Click the same button again
5) Toolbar jumps to random position

and second problem (probably also connected with hiding toolbar):

_Maximum call stack size exceeded_
![image](https://user-images.githubusercontent.com/6122467/27155815-ac0a0050-515a-11e7-81d4-82fea412b9cd.png)

How to reproduce it (on Chrome, ver. 59.0.3071.86, on FF it works properly): 
1) Select some text
2) Click bold button (or other)
3) Click outside '.tab-container-editor' on the right padding of this div (on left it works, really strange :P)
3) Click button again
4) You should have error log in console

It could be probably fixed if you hide toolbar on blur event or on click outside event
Regards,
Konrad

**Comment by ricobl** [comment]
Hey @sevikon!

Thanks for reporting, I was able to reproduce these errors on my machine with the latest versions of Chrome (59.0) and Firefox (54.0).

Hiding the toolbar on blur is a bit tricky, when editing an entity the editor loses focus but the toolbar should stay visible:

![image](https://user-images.githubusercontent.com/134148/27287541-6e6acc06-54da-11e7-9233-55d440e3828d.png)

It could work using two conditions to showing the toolbar: editor focus or entity focus.

And I have no idea about the `Maximum call stack size exceeded`, we should investigate further.

Are you willing to tackle these problems @sevikon?

**Comment by remolueoend** [comment]
Hey guys,

We observed probably the same `Maximum call stack size exceeded` issue. I already posted a comment on another issue: https://github.com/globocom/megadraft/issues/157#issuecomment-313147821

I'm working on a small PR but might be a little bit hacky due to our project deadlines (sorry in advance :3.
