### ISSUE TITLE
Nested Lists?

### ISSUE THREAD

**Issue by ryuheiyokokawa** [globocom/megadraft#164]
Is it possible to do nested lists?  Is this an option (as in I'm stupid?) or does this not exist?
By nested lists, below is what I mean:

- Not nested
  - Nested

Thanks!

**Comment by marcelometal** [comment]
Hi @ryuheiyokokawa,
this feature is not implemented in Megadraft, but [DraftJS support it](https://draftjs.org/docs/advanced-topics-nested-lists.html).

I think it would be a nice feature to have, feel free to open a PR. The initial point to start is the MegadraftEditor [onTab method](https://github.com/globocom/megadraft/blob/2bcf3f8828166ab77095ff80e04b62ea45bb7611/src/components/MegadraftEditor.js#L114). Don't hesitate to contact me if you have any questions.

**Comment by ricobl** [comment]
Hey @ryuheiyokokawa, I'm closing the issue but please feel free to comment!
