### ISSUE TITLE
Draft JS on Andriod and iOS

### ISSUE THREAD

**Issue by rohitpal99** [globocom/megadraft#166]
Hi all,
This is not a issue, I wanted to ask a query for knowledge.
I know that facebook uses draft js for its mentions? I wanted to know how draft js is used in android applications or iOS? or They don't use this on Andriod devices at all?

My use case is If I have a rich text content editor on web. How would I go with editing same content on iOS devices or andriod devices (should I use draft js inside WebView ?) or go with something else altogether

Thanks,
Rohit

**Comment by ricobl** [comment]
Hey @rohitpal99!

I'm not sure how Facebook does mentions on mobile apps, maybe you can ask for advices on the [project page](https://github.com/facebook/draft-js) or on [DraftJS' Slack](https://draftjs.slack.com).
