### ISSUE TITLE
Custom icons for custom entities

### ISSUE THREAD

**Issue by CraigLu** [globocom/megadraft#167]
I have been trying to use some custom icons for new entities that I am creating for the tooltip actions but I haven't been able to get the actions array to accept what I put in for the icon. Is there any requirements that need to be met for custom icons to be displayed properly?

**Comment by ricobl** [comment]
Hey @CraigLu, the only requirement is that icons need to be a React component.

All built-in icons are SVGs converted to components. You should replace the `fill` attribute of `path` elements with `currentColor` to allow icons to inherit CSS colors (light gray as default, white on hover and blue when active).

Here is the delete icon for a reference:
https://github.com/globocom/megadraft/blob/master/src/icons/delete.js

Why did you close the issue? Is it solved already?

Feel free to join us on our `#megadraft` channel on DraftJS' Slack if you have additional questions:
http://draftjs.slack.com

Register here: https://draftjs.herokuapp.com/
