### ISSUE TITLE
Adjust immutable dependency version to optimize bundle size

### ISSUE THREAD

**Issue by LyTranCong** [globocom/megadraft#168]
<img width="688" alt="screen shot" src="https://user-images.githubusercontent.com/648415/29491796-ce79764c-8590-11e7-8c9d-6c1f72b1df03.png">

DraftJS 0.10.1 just use `"immutable": "~3.7.4"` while MegaDraft use `"immutable": "^3.8.1"`.

**Comment by marcelometal** [comment]
Hi @LyTranCong,

Immutable [3.7.4](https://github.com/facebook/immutable-js/blob/3.7.4/dist/immutable.min.js) has **55.3 KB** and [3.8.1](https://github.com/facebook/immutable-js/blob/v3.8.1/dist/immutable.min.js) has **55.7KB**.
The difference is **0.4KB**, did you see that ?

**Comment by LyTranCong** [comment]
Hi @marcelometal ,
If the version range is mismatch, npm will install both versions and webpack will include both in the bundle. In this case, 3.7.4 for DraftJS and 3.8.1 for MegaDraft!

**Comment by marcelometal** [comment]
@LyTranCong,  Ah! Good point... Thank you!
