### ISSUE TITLE
Allow onTab to be overridden

### ISSUE THREAD

**Issue by CameronAckermanSEL** [globocom/megadraft#172]
Megadraft suppresses any onTab handlers sent through props. This looks like its because the default tab behavior tabs out of draft and into other controls. 

Please allow users of megadraft to override the default onTab behavior megadraft provides (e.preventDefault()).

**Comment by CameronAckermanSEL** [comment]
#174

**Comment by joepio** [comment]
Since `event.preventDefault()` is called before the `onTab` prop event is called in [MegadraftEditor.js](https://github.com/globocom/megadraft/pull/174/files), using the tab key still does not work the way you'd expect it to work - even if you pass a custom event.

Shouldn't this:
```` javascript
onTab(event) {
  event.preventDefault();
  if (this.props.onTab) {
    this.props.onTab(event);
  }
}
````

Become this?
```` javascript
onTab(event) {
  if (this.props.onTab) {
    this.props.onTab(event);
  } else {
    event.preventDefault();
  }
}
````

**Comment by joepio** [comment]
I believe overriding the default behavior of using the tab key in an input field is bad practice. It severely impacts accessibility. Keyboard only users can't use megadraft.

I'll change my suggestion. Remove the `preventDefault`, change `onTab` to:
``` javascript
onTab(event) {
  if (this.props.onTab) {
    this.props.onTab(event);
  }
}
```

**Comment by CameronAckermanSEL** [comment]
(So there's no illusions on this, I have no intention on changing this behavior as I don't use Draft anymore, so I think you'll need to come up with your own PR)

**Comment by joepio** [comment]
Thanks for the quick reply! I opened a PR, #197
