### ISSUE TITLE
Css scale transform causes incorrectly positioned tooltip

### ISSUE THREAD

**Issue by ryanlegler** [globocom/megadraft#175]
If i add a css scale transform to a containing element of the megadraft component the tooltip will render incorrectly.

Example:
https://rich-text-ceiezbqwvc.now.sh

My guess is that this behavior is related to how how the tooltip measurements are being calculated.
Looks like getBoundingClientRect() is being used which will measure the position after the css transformation. 
https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Determining_the_dimensions_of_elements

These values are then passed to the component to render... then scaled again by the css

Has anyone run up against this issue before? Is anyone aware of a workaround?

**Comment by ricobl** [comment]
Hey @ryanlegler, I haven't heard about this problem before.

Looks like the example is down.

Do you have a solution in mind? Would you like to submit a PR?

**Comment by ryanlegler** [comment]
@ricobl thanks for the response, yeah it's an interesting problem. I've been running into all sorts of issues like this when working in a css scaled context.

As far as a solution it looks like how other components are dealing with the issue is by allowing a scale prop to be passed in. The scale prop is then used to calculate all of the pixel coordinates used when placing the tooltip.

Here's an example of a fix for the react-draggable library:
https://github.com/mzabriskie/react-draggable/pull/217/files

I hope this helps

**Comment by glauberm** [comment]
Hi. Could you provide me with some steps to reproduce this issue? Thanks.

**Comment by osmarpetry** [comment]
@ryanlegler do you can be more clear about what is happening?
