### ISSUE TITLE
Plugin block not inserting!?

### ISSUE THREAD

**Issue by joelmoss** [globocom/megadraft#179]
I have created an image plugin to play and test with, and the Button appears and works, but the Block never gets inserted at all!

Here is my plugin code...

```javascript
import Button from './button'
import Block from './block'

export default {
  title: 'Image',
  type: 'image',
  buttonComponent: Button,
  blockComponent: Block
}
```

```javascript
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import { MegadraftIcons, insertDataBlock } from 'megadraft'

export default class Button extends Component {
  static propTypes = {
    onChange: PropTypes.func,
    editorState: PropTypes.object,
    className: PropTypes.string,
    title: PropTypes.string
  }

  onClick = () => {
    const src = window.prompt('Enter a URL')
    if (!src) return

    const data = { src: src, type: 'image', display: 'medium' }
    this.props.onChange(insertDataBlock(this.props.editorState, data))
  }

  render() {
    return (
      <button
        className={this.props.className}
        type="button"
        onClick={this.onClick}
        title={this.props.title}
      >
        <MegadraftIcons.ImageIcon className="sidemenu__button__icon" />
      </button>
    )
  }
}
```

```javascript
import React, { Component } from 'react'
import PropTypes from 'prop-types'

export default class Block extends Component {
  static propTypes = {
    data: PropTypes.object
  }

  render() {
    console.log('hello!!!!') // this is never called!!!
    return <img src={this.props.data.src} />
  }
}
```

Any help would be appreciated. thx

**Comment by k-zakhariy** [comment]
Have you inserted your plugin to MegadraftEditor component ?

**Comment by joelmoss** [comment]
Yup, with `plugins={[imagePlugin]}`

**Comment by k-zakhariy** [comment]
checkout this source code - https://github.com/globocom/megadraft-related-articles-plugin
good example how to write own plugins

**Comment by joelmoss** [comment]
Yeah I have, but just tried to add that plugin without changes, and that does the same thing... the button shows up, but nothing happens after clicking it. So again, it's like the block is not working at all. No errors! No warnings! :(

**Comment by joelmoss** [comment]
Ok, so I've found the cause, although I've not yet discovered the why :|

The block completely fails to render when using a `ref` on the editor...

```javascript
<MegadraftEditor
  ref={ed => this.myEditor = ed}
  editorState={this.state.editorState}
/>
```

Remove the `ref` attribute and all works great. 

Any ideas why this would be?

**Comment by marcelometal** [comment]
No idea! =/

So, I'm closing this for now. If you have any further questions on this issue, please reopen it.

**Comment by joelmoss** [comment]
Well considering this is a bug, I would suggest you keep this bug report open perhaps? 🤔

**Comment by marcelometal** [comment]
@joelmoss for me, this is not a Megadraft bug...

I've created a new plugin using [Megadraft`s plugin generator](http://megadraft.io/#/docs/plugins) and replaced it with your code ([Block](https://github.com/marcelometal/my-image-plugin/blob/master/src/Block.js) and [Button](https://github.com/marcelometal/my-image-plugin/blob/master/src/Button.js)). I've also added the [ref prop in the MegadraftEditor component](https://github.com/marcelometal/my-image-plugin/blob/master/demo/main.js#L40).

Take a look at: https://github.com/marcelometal/my-image-plugin
