### ISSUE TITLE
[question] Do you known if is there a self-hosted blog using megadraft?

### ISSUE THREAD

**Issue by lakano** [globocom/megadraft#182]
Hi,

Megadraft is awesome, thank you very much!
After some searches, I don't found any blog using megadraft. 
This could be a serious advantage to choose a blog self-hosted platform.

Regards,

**Comment by authoredniko** [comment]
Hi @lakano : www.authored.io are about to launch a self hosted blog platform built on draftJS :)

Would be happy to share more details if you're interested 

N

**Comment by lakano** [comment]
Thank you @authoredniko 
I've registered to the alpha. You seems to be the developer of this project (because of your nickname), could you confirm we could download it to install it on our own server?
Regards,

**Comment by marcelometal** [comment]
Hi @lakano, thank you!

I don't know any self-hosted blog using Megadraft. So, I'm closing this for now. If you have any further questions on this issue, please reopen it.
