### ISSUE TITLE
Allow target blank in links

### ISSUE THREAD

**Issue by eskimoblood** [globocom/megadraft#184]
Add the moment there is no way to make links open in a new tab. When the link is [created](https://github.com/globocom/megadraft/blob/master/src/entity_inputs/LinkInput.js#L40), only the url is set. Would it be possible to add at least a prop to make all links open in new tab, or even better to add the possibility to let the user set this when creating a link.

**Comment by CentaurWarchief** [comment]
@eskimoblood you may be able to achieve something like this by doing:
```JS
function TargetBlankLink({ entityKey, children, contentState }) {
  const { url } = contentState.getEntity(entityKey).getData();

  return (
    <a className="editor__link" href={url} title={url} target="_blank">
      {children}
    </a>
  );
}

TargetBlankLink.propTypes = {
  entityKey: PropTypes.string.isRequired,
  children: PropTypes.any.isRequired,
  contentState: PropTypes.any.isRequired,
};

const decorators = new CompositeDecorator([
  {
    strategy: createTypeStrategy('LINK'),
    component: TargetBlankLink,
  },
]);

const stateWithDecorators = EditorState.set(editorState, {
  decorator: decorators,
});
```

Then all you need to do is pass `stateWithDecorators` down to `<MegadraftEditor>`

**Comment by macrozone** [comment]
see also docs https://github.com/globocom/megadraft/blob/master/docs/custom_entities.md

**Comment by marcelometal** [comment]
Hi @eskimoblood, If you have any further questions on this issue, please reopen it.
