### ISSUE TITLE
Bad rendering when attempting to remove a blockquote

### ISSUE THREAD

**Issue by andreyvital** [globocom/megadraft#187]
Hey guys, check this out:

![kapture-2018-01-25-at-22 01 08](https://user-images.githubusercontent.com/967317/35418839-e8ac9244-021b-11e8-877d-572d72e8d283.gif)

I haven't tried to debug it myself yet, but it seems to be a bad behavior. Steps to reproduce:

1. Head out to http://megadraft.io;
2. Clear all the content;
3. Type some bla bla bla bla bla, then Command + A (I'm using a Mac);
4. In the toolbar opened for the selection, select `"` blockquote;
5. Hit backspace with the same selection.

I wasn't able to reproduce this on draftjs.org — maybe it's a bug on their end, but I'm reporting here just so you guys know it happens...

**Comment by vierno** [comment]
I can confirm this, it's related to the styles of the blockquotes and placeholder.

**Comment by tacoelho** [comment]
Which browser are you using to view it? I just did the same steps on Chrome (Windows 10) and it seems fine to me.

**Comment by lucasferreiralimax** [comment]
Hello @andreyvital , I created the solution [position placeholder](https://github.com/globocom/megadraft/pull/254)

**Comment by JeanPinzon** [comment]
Fixed by https://github.com/globocom/megadraft/commit/ec5a4a96c5cdc34ef4ad1fec45c1bffd43305cda
