### ISSUE TITLE
Toolbar vertical positioning

### ISSUE THREAD

**Issue by Minivera** [globocom/megadraft#193]
When using megadraft in a limited height window (Example, IFrame), the editor will often find itself with the first line being to far up to display the toolbar.

For example, this would happen if you scrolled too far up in megadraft.io

![2018-02-20 11_40_06-megadraft - draft js rich text editor](https://user-images.githubusercontent.com/20424444/36436721-169e77f0-1633-11e8-81d2-189c57756c0f.png)

However, the expected behavior would be something akin to this : 

![2018-02-20 11_39_41-megadraft - draft js rich text editor](https://user-images.githubusercontent.com/20424444/36436748-2c284cb8-1633-11e8-95ee-e0b258c17783.png)

I am implementing megadraft into my application and I already had to create a fork to fix some issues with iframes, as such, I used this fork to try and build a fix for this issue as well. You can find it in these two files.

https://github.com/Minivera/megadraft/blob/master/src/components/Toolbar.js
https://github.com/Minivera/megadraft/blob/master/src/utils.js

The second screenshot taken above is taken from my fork. 

I also used this chance to fix both #143 and #190 as well, though my solution may not be the best for both. Unfortunately, my fixes also broke one of the unit tests for the toolbar which checks for an offset of 14px for the toolbar, as the toolbar would instead fix itself under the selection in the test case.

Considering this, I though I'd first create an issue to check and discuss a possible solution before going for a PR.

**Comment by vierno** [comment]
Hello @Minivera, we generally solve this problem adding enough margins to the elements so there's enough space for the toolbar. We are going to break this behavior if we use the editor bounds to calculate if the toolbar should be rendered under the selection.

Somehow we need to check this and if the toolbar would be rendered outside of the document's visible area.

**Comment by Minivera** [comment]
My specific case is a page builder inside an IFrame where the user is free to position the editor wherever he likes. This cause a big issue where the toolbar would very often be cut by the iframe's bounds and there is nothing I could do about it expect ask the user to add breaklines.

In the second screenshot, I fixed the issue by using this condition : 

`offsetTop - minOffsetTop - toolbarHeight + editorBounds.top < 0`.

This works because the offset is always relative to the current scroll position and thus lesser than 0 if the toolbar is even one pixel cut by the visible area.

I guess using editorBounts.top here could break like you said, what property should I use to make this check instead?

**Comment by vierno** [comment]
I don't know how could we do a better check... I believe we can use the solution you proposed, could you please open a PR?

**Comment by Minivera** [comment]
Sure, I will do that when I get back at my workstation tomorrow.
