### ISSUE TITLE
Custom toolbar actions

### ISSUE THREAD

**Issue by AlessiaCorsini** [globocom/megadraft#207]
Hello everyone, I just started to work with megadraft so forgive me if I missed something.
In my project I would like to replace the toolbar actions with some custom ones but I am stuck. In your documentation you are using an 'actions' variable 
```
const customActions = actions.concat([
      {type: "inline", label: "U", style: "UNDERLINE", icon: UnderlineIcon}
    ])
```
but from were should I get it from?  Thank you in advance

**Comment by marcelometal** [comment]
Hi @AlessiaCorsini, you can get it from:

 ```import actions from "megadraft/lib/actions/default"```

I`ve fixed the docs, thank you!
