### ISSUE TITLE
Android: onChange returns empty text

### ISSUE THREAD

**Issue by Yuripetusko** [globocom/megadraft#209]
When I type something in browser or ios  and then do `editorStateToJSON(this.state.editorState)` I can see value i typed in `text` field, however on android no matter what i type it's always empty and then when i blur out of the textarea or press enter for new line, text simply dissapears

```
"{
  "blocks": [
    {
      "key": "1e9se",
      "text": "",
      "type": "unstyled",
      "depth": 0,
      "inlineStyleRanges": [],
      "entityRanges": [],
      "data": {}
    }
  ],
  "entityMap": {}
}"
```

Same issue on megadraft.io demo editor

**Comment by Yuripetusko** [comment]
Looks like draft.js problem

https://github.com/facebook/draft-js/issues/1077

**Comment by mogavin** [comment]
> Looks like draft.js problem
> 
> [facebook/draft-js#1077](https://github.com/facebook/draft-js/issues/1077)

Hi, @Yuripetusko ! First, sorry for the delay. This bug has apparently been resolved in [this draft.js PR](https://github.com/facebook/draft-js/issues/1895), incorporated in the [draft.js release v0.11.0](https://github.com/facebook/draft-js/releases/tag/v0.11.0) . As soon as we update for this version of draft we communicate here.
