### ISSUE TITLE
Megadraft internal i18next instance messes up App's one

### ISSUE THREAD

**Issue by eduludi** [globocom/megadraft#214]
Since `0.5.0`, importing Megadraft causes an override of my app's i18next instance. In other words, in the moment the component with Megadraft `import` is loaded, all others translations show only their key values.

Can be i18next disabled (or removed) from Megadraft, and provide custom translations as props, like other component libraries handle i18n. Here is an example: 

```jsx
const i18n = {
  linkPlaceholder: "Type the link and press enter",
  linkInvalid: "Invalid Link",
  pluginMissing:  (type) => `Can't show plugin, component "${type}" not found.`,
  blockList: 'Block List'
}

<MegadraftEditor 
  editorState={editorState}
  onChange={this.onChange}
  i18n={i18n}
  />
```

Removing the dependency can give Megadraft more flexibility, as users will be able integrate the i18n library they want, without bundling a library they won't use. It will also mean that Megadraft won't need to support a set of languages (if they need something else, developers can take care of that).

Another option is to be able to provide a custom i18next instance that will be used instead of Megadraft's one:

```jsx
import i18n from '../my/own/i18n' // <- this will also include Megadraft translations

<MegadraftEditor 
  editorState={editorState}
  onChange={this.onChange}
  i18n={i18n}
  />
```

**Comment by vierno** [comment]
@eduludi, yes, Megadraft should not take control and override i18next, your first suggestion looks good to me.

**Comment by marcelometal** [comment]
#219 fixes it, so I'm closing this issue.
