### ISSUE TITLE
Android: crash when hitting backspace on empty input box

### ISSUE THREAD

**Issue by tobiasmayr** [globocom/megadraft#215]
Hi,

I tried this on megadraft.io, because interestingly it also happens on slate.js (the demo for slatejs):

- open the site megadraft.io in a browser on Android
- delete all the text that is there
- hit backspace once more
- the editor crashes

Tested with Google Chrome and Firefox.

**Comment by allanassis** [comment]
Hi @tobiasmayr ,
We don't have plans to work on a mobile solution in the short term, but it could happen in the future.

**Comment by tobiasmayr** [comment]
Oh sorry, didn't notice that this was not a mobile project :)
