### ISSUE TITLE
Lose Text Options when hooking up CSS 

### ISSUE THREAD

**Issue by abomb14c** [globocom/megadraft#217]
I feel crazy stupid right now but when i hook up the the css file the layout changes to the dropdown with options for video and pictures but I lose all of the text options?

**Comment by abomb14c** [comment]
also, how do i get an invite to the slack channel? Documentation isn't helping.

**Comment by vierno** [comment]
@abomb14c the slack channel should not require an invite, I believe you can just create an account with your e-mail.

By losing all the text options you mean the toolbar does not show up when you select the text? Can you find it on the browser inspector?

**Comment by marcelometal** [comment]
@abomb14c  ping?

**Comment by mogavin** [comment]
Hi @abomb14c ! Still have this question? I'll close for now, but you can reopen it if you want to continue 👍
