### ISSUE TITLE
Sidebar with Icons

### ISSUE THREAD

**Issue by vierno** [globocom/megadraft#22]
Create a sidebar with media icons to add image/video.

![screen shot 2016-04-27 at 4 59 34 pm](https://cloud.githubusercontent.com/assets/681628/14866318/79d18f9c-0c99-11e6-9a55-8f11031cb0d9.png)

**Comment by ricobl** [comment]
Can we consider this done @vierno ?

We don't have the full behaviour but we have a working sidebar.

**Comment by vierno** [comment]
Yeah, closing it!

**Comment by ricobl** [comment]
Cool! Thanks!
