### ISSUE TITLE
Pass editorState to ToolbarItem Icon

### ISSUE THREAD

**Issue by estermer** [globocom/megadraft#227]
Currently for custom toolbar actions, there is a key to add an icon. it would be nice to enable passing data to that icon so it can edit the editorState instead of jumping to a new input entity.

For example i could render a dropdown for font sizes or a popover with a color picker.

So in a custom toolbar action it would look something like this:

```js
{
    type: "custom",
    icon: props => <CustomIcon editorState={props.editorState}/>,
    action(editorState, onChange) {},
},
```

**Comment by mogavin** [comment]
Hi @estermer! Still interested in improving this feature? I'll close for now, but you can reopen it if you want to continue 👍
