### ISSUE TITLE
Toolbar covered up by Iphone text selection options

### ISSUE THREAD

**Issue by bpurtz** [globocom/megadraft#234]
When viewing the editor on an iphone, highlighting any text will also bring up the native iphone text options, obscuring the toolbar. Making the toolbar appear below the selection on small screens instead of above could be an easy fix.

**Comment by mogavin** [comment]
Hi @bpurtz ! First, sorry for the delay. Megadraft does not yet have full mobile compatibility (like Draft.js) yet, but we are planning to include it in nearby roadmaps. Keep an eye !

**Comment by an2323** [comment]
Hi @mogavin, any updates here?

**Comment by mogavin** [comment]
Hi, @an2323 ! Megadraft does not yet officially support mobile devices. An alternative to using it on these devices is to disable the toolbar and rich text buttons (in native iphone text options):

```
const disableRichTextButtonsStyle = `.public-DraftEditor-content[contenteditable=true] {
      -webkit-user-modify:read-write-plaintext-only;
      user-modify: read-write-plaintext-only;
 }`

//inside component render
<Fragment>
 <style>{disableRichTextButtonsStyle}</style>
 <div style={{ marginLeft: 63 }}>
   <MegadraftEditor
     editorState={this.state.editorState}
     onChange={this.onChange}
     Toolbar={() => null}
   />
 </div>
</Fragment>
```
