### ISSUE TITLE
Content not updating as per index in Drag n Drop plugin but its actually updating Array of object, Attached video of my app

### ISSUE THREAD

**Issue by codergkd** [globocom/megadraft#235]
Please go through below URL actually content is not rendering as per data after drag n drop
https://www.loom.com/share/8745e5855b5441008eac222f6bd644d5

**Comment by mogavin** [comment]
Possibly related to #141

**Comment by mogavin** [comment]
Hi @codergkd, sorry for the delay. This issue is related to the Megadraft's lack of integration with draft-js-plugins. I'll close it by now and ask you to follow the issue #141. Thanks !
