### ISSUE TITLE
Toolbar non-responsive

### ISSUE THREAD

**Issue by Kinyugo** [globocom/megadraft#239]
The toolbar does not display correctly on small screens or even larger ones when the text is at the start of the screen.
Some parts of it are hidden

**Comment by ThaysPrado** [comment]
Hi! Can I help you with this?

**Comment by Kinyugo** [comment]
Am not using megadraft at the moment, but for future references you can leave your thoughts.

**Comment by glauberm** [comment]
I can work on this one. Could you provide me with steps to reproduce the issue? I'm not sure what problem are you exactly referring to.

**Comment by LuAnderson** [comment]
Please, look in https://github.com/globocom/megadraft/pull/258
