### ISSUE TITLE
Can't edit after removing container

### ISSUE THREAD

**Issue by ri8ika** [globocom/megadraft#243]
I am not using CommonBlock as per plugin example. I have a button which calls the following function to remove the container. But after this the content is not editable. It only becomes accessible after window is reloaded.
```
this.props.container.remove()
```

I think I need to update the editorState. But not sure how to update it?

**Comment by SvyatoslavPozhydaev** [comment]
+1

**Comment by SvyatoslavPozhydaev** [comment]
@ri8ika this problem occurs if you use a focusable element to invoke container methods

**Comment by SvyatoslavPozhydaev** [comment]
@ri8ika you can add stopPropagation on root element block
`
import React, { PureComponent } from 'react';
class Block extends PureComponent {
   render() {
     return (
        <div
             className="root-ement-block"
              onFocus={(e) => e.stopPropagation()}
              onBlur={(e) => e.stopPropagation()}
        >
            <button onClick={() => this.props.container.remove()}>remove</botton>
            ....
        </div>
     )
  }
}
`
