### ISSUE TITLE
Renamed React Methods: componentWillReceiveProps

### ISSUE THREAD

**Issue by jleck** [globocom/megadraft#247]
Hi,

Has anyone tackled removing componentWillReceiveProps etc from the codebase? If not, I'll work on that and submit a PR.

**Comment by icaromh** [comment]
@jleck We will love your contribution 🎉

**Comment by gagandeepp** [comment]
Is this still open I can take a look on this?

**Comment by jleck** [comment]
I haven't started looking at it yet, so fire away!

**Comment by Andy9822** [comment]
@jleck  
Were you planning to remove those methods and refactoring the parts where they are called or just rename them to its UNSAFE_... version?

I can help with this issue tho

**Comment by jleck** [comment]
@Andy9822 I was planning to refactor rather than rename to unsafe.
