### ISSUE TITLE
Website menu bar show mispositioned Left Dropdown

### ISSUE THREAD

**Issue by ScottiBR** [globocom/megadraft#248]
## Context
When you are inside the website, if you click on the *Documentation menu*, the scroller will create a weird behavior showing the Left Dropdown at nowhere. There's anyone working on that, or can i submit a PR?

## Steps to Reproduce the Bug
- Desktop Google Chrome Version 77.0.3865.90
- Open website
- Scroll half of the current viewport, enough to see the documentation menu
- Click on documentation menu

![image](https://user-images.githubusercontent.com/34926591/65933313-6a301f80-e3e7-11e9-9924-4c0325588efe.png)

**Comment by iagocavalcante** [comment]
Can i fix this ?
