### ISSUE TITLE
Toolbar horizontal positionning

### ISSUE THREAD

**Issue by cosydney** [globocom/megadraft#251]
I'm looking for some ways to adapt the toolbar when it meets a border, like so: (here we cannot see bold and italic button)

![image](https://user-images.githubusercontent.com/10532381/66308447-7ea07a80-e907-11e9-8c26-33e5ecabf683.png)

**Comment by merelj** [comment]
I'd like to take this one

**Comment by LuAnderson** [comment]
Please, look in https://github.com/globocom/megadraft/pull/258
