### ISSUE TITLE
Change class components to functional components

### ISSUE THREAD

**Issue by Andre-rsfc** [globocom/megadraft#264]
- I dont have assurance its is what do you want, but  I think the code would be more current and beautiful!

**Comment by Andre-rsfc** [comment]
I started doing this by changing some simpler components #265

**Comment by aristotelesbr2014** [comment]
+ 1

**Comment by aristotelesbr2014** [comment]
Is it possible use like as hooks? For me don't works :(

**Comment by mogavin** [comment]
> Is it possible use like as hooks? For me don't works :(

Checking on issue #290

**Comment by mogavin** [comment]
Closing this issue according to [resolution](https://github.com/globocom/megadraft/pull/265#issuecomment-564170922) in #265
