### ISSUE TITLE
SideBar error : this.props.onAction

### ISSUE THREAD

**Issue by philohelp** [globocom/megadraft#280]
Using the latest version of React, I can't use the sidebar anymore (I plugged the megadraft-image-plugin on it). Maybe related to the rewrite of componentWillReceiveProps ? 

<img width="526" alt="Capture d’écran 2019-11-26 à 17 44 24" src="https://user-images.githubusercontent.com/12623963/69654127-92996a80-1074-11ea-9eeb-e69821385f9c.png">

**Comment by icaromh** [comment]
Thanks, @philohelp for reporting it. We are releasing a new version fixing this issue. 

[This PR](https://github.com/globocom/megadraft/pull/276) should fix the problem.

**Comment by icaromh** [comment]
@philohelp it's done. You can use the latest version (0.6.12) installing from NPM.

`npm install megadraft@latest`
