### ISSUE TITLE
Mispositioning toolbar

### ISSUE THREAD

**Issue by mogavin** [globocom/megadraft#291]
> ### **_Obs: For easier tracking, we've grouped issues related to mispositioning toolbar._**

## Related issues
#251
#239
#199
#143

## Related PR's
#258
#294

## Expected Behavior
When the toolbar encounters a border, it must be repositioned.

![image](https://user-images.githubusercontent.com/6331103/71293837-6ad8b200-2355-11ea-992d-e5bdb424ccbf.png)

## Current Behavior
When the toolbar encounters a border, it does not reposition and appears cut off.

![image](https://user-images.githubusercontent.com/6331103/71293863-85ab2680-2355-11ea-8927-ba8d4a656a64.png)

**Comment by wdtamagi** [comment]
I sent a PR to fix this.

**Comment by wdtamagi** [comment]
I believe there is a conflict with Codacy (pipeline) rules and eslint rules for semicolons on my PR #294

**Comment by mogavin** [comment]
Thank you for your contribution, @wdtamagi . We will look at the issues raised and we will give you feedback shortly.

**Comment by mogavin** [comment]
Merged in release [0.7.0-alpha.0](https://github.com/globocom/megadraft/releases/tag/0.7.0-alpha.0)
