### ISSUE TITLE
Uncaught Invariant Violation: Minified React error #200

### ISSUE THREAD

**Issue by mikekoro** [globocom/megadraft#312]
This is the error I get when I attempt to run a dev version of the plugin. Is there any way to  fix it?

The reason I am trying to run it in dev mode is to add an additional button to "sidebar__menu" (not a plugin that goes inside the drop down menu, but a "top level button", which should be right next to the current sidebar button). Perhaps, there is a way to achieve it through "sidebarRendererFn"? Or just simply add a button to each block. Anything would work in my case. @

**Comment by mogavin** [comment]
Hi, @mikekoro ! 

Currently the only extension available is the insertion of new plugins as additional button in the `Sidebar`. The functionality you mentioned would be possible with the insertion of a new `SideMenu` component in the `Sidebar`. Follow the [dev mode procedures](https://github.com/globocom/megadraft#developing), but access `localhost:8080/#` (without the `/dev`, we will fix that ), try this duplication and see if it shows the desired behavior:

_src/plugin/Sidebar.js_
```
<ul className="sidebar__sidemenu-wrapper">
  <SideMenu
      i18n={this.props.i18n}
      editorState={this.props.editorState}
      onChange={this.onChange}
      plugins={this.getValidSidebarPlugins()}
      maxSidebarButtons={this.props.maxSidebarButtons}
      editorHasFocus={this.props.editorHasFocus}
      hideSidebarOnBlur={this.props.hideSidebarOnBlur}
      modalOptions={this.props.modalOptions}
   />
   //Duplicated
   <SideMenu
       i18n={this.props.i18n}
       editorState={this.props.editorState}
       onChange={this.onChange}
       plugins={this.getValidSidebarPlugins()}
       maxSidebarButtons={this.props.maxSidebarButtons}
       editorHasFocus={this.props.editorHasFocus}
       hideSidebarOnBlur={this.props.hideSidebarOnBlur}
       modalOptions={this.props.modalOptions}
     />
 </ul>
```

**Result:**
![duplicated-side-menu](https://user-images.githubusercontent.com/6331103/77931420-8885b380-7282-11ea-81f8-8ba492a2a16a.gif)
<br/><br/>
**If so, we would gladly accept a PR to review it 😃 !**
