### ISSUE TITLE
List Item Symbol and Placeholder Both Appear at the same time

### ISSUE THREAD

**Issue by karrie-helloalice** [globocom/megadraft#319]
# -- Bug Report --

## Expected Behavior
Placeholder is not present when there is a list item bullet/number in the editor.

## Current Behavior
Placeholder and list element are both present within the editor.

## Steps to Reproduce
1. Within a megadraft editor, add any number of li elements
2. Highlight the list items
3. Press 'delete'
4. You should see the li element overlapping with the placeholder

## Browser, device, and OS
**Chrome**: Version 84.0.4147.89 (Official Build) (64-bit)
**macOS**: Version 10.14.6 (18G6020)

## Screenshots

![Screen Shot 2020-07-29 at 18 38 27](https://user-images.githubusercontent.com/56563151/88864593-32426600-d1cb-11ea-8b4a-d49890a8d7c1.png)

----- 
### Screenshots of Step by Step Reproduction

1. ![Screen Shot 2020-07-29 at 18 37 50](https://user-images.githubusercontent.com/56563151/88864635-48e8bd00-d1cb-11ea-8d81-534b02506138.png)
         - User is in megadraft editor

2. ![Screen Shot 2020-07-29 at 18 38 23](https://user-images.githubusercontent.com/56563151/88864650-4d14da80-d1cb-11ea-8ca0-63ea15b33107.png)
         - User has added multiple list item elements

3. ![Screen Shot 2020-07-29 at 18 38 27](https://user-images.githubusercontent.com/56563151/88864660-50a86180-d1cb-11ea-96b6-0c1c3688fecf.png) (this is the same image as the first screenshot)
         - User deletes elements but still sees bullet

**Comment by lousander** [comment]
Hi Karrie!
Thank you very much for you report :)
We will take a look into it soon. We also accept contributions if you're interested in tackling this issue ;)

**Comment by LFRusso** [comment]
Is this issue still available? I would like to work on it!

**Comment by lousander** [comment]
Hi, @LFRusso. Sorry for the late reply. I think we already have 2 open Pull Requests, awaiting review, for this issue.

**Comment by ShraddhaGeek** [comment]
Can I take this ?
