### ISSUE TITLE
After updating megadraft the editor is always not editable unless I reload

### ISSUE THREAD

**Issue by HakimJu** [globocom/megadraft#338]
# -- Feature --
Supply setReadOnly to the Block component in order to  change and manipulate readOnly state

## Description
There is a use case when trying to implement creation/update of block via a Modal. The update modal is being triggered when clicking on the block output 
<img width="857" alt="Screenshot 2021-03-19 at 17 50 06" src="https://user-images.githubusercontent.com/25585534/111815219-b58c0580-88db-11eb-9416-e01f0c56df0f.png">

On clicking on the block 

<img width="1321" alt="Screenshot 2021-03-19 at 17 49 53" src="https://user-images.githubusercontent.com/25585534/111815232-b7ee5f80-88db-11eb-8cca-ddb624f979bb.png">

When submitting or closing the modal the editor is always not clickable unless I reload the page seems like focus on MediaWrapper is always true although the modal is closed .

The issue seems to be general with all plugins I implemented using Modals. The fix was change setReadOnly from Block component depending on the modal state (opened/closed)

**Comment by lousander** [comment]
Hi @HakimJu. Our Stalebot closed this issue automatically, but I reopened because it's in our schedule and we'll take a look at it soon. :)

**Comment by igor-giusti** [comment]
Hi, @HakimJu the `setReadOnly` and `setInitialReadOnly` are available in `props.blockProps`. You can use them to manipulate the editor's editable state as requested.
