### ISSUE TITLE
We need docs!

### ISSUE THREAD

**Issue by vierno** [globocom/megadraft#36]
There should be at least some basic documentation on how to run megadraft locally...

**Comment by oyeanuj** [comment]
+1 to this. If there can be some docs on how custom media blocks work and how to add newer similar features, that would be even more swell :)

**Comment by ricobl** [comment]
Looks like we have docs now: http://globocom.github.io/megadraft/#/docs/plugins?_k=ff4861

@oyeanuj: would you like to review? Does it work for you?
