### ISSUE TITLE
NodeJS 16 support

### ISSUE THREAD

**Issue by marcelometal** [globocom/megadraft#368]
Build failed: https://github.com/globocom/megadraft/runs/5139464250?check_suite_focus=true

**Comment by natamartins** [comment]
O log não foi encontrado. Ele pode ter sido excluído com base nas configurações de retenção.

**Comment by taismassaro** [comment]
I also got this issue running it locally and here's an updated log from my PR: https://github.com/globocom/megadraft/actions/runs/3174732877/jobs/5171891434
