### ISSUE TITLE
Not Seeing Text Block in Menu 

### ISSUE THREAD

**Issue by S1ark** [globocom/megadraft#380]
# -- Bug Report --

## Expected Behavior
Text Block to be shown as part of left Menu 

## Current Behavior
Not Seeing Text Block in Menu 

## Steps to Reproduce
```
  <MegadraftEditor
            editorState={editorState}
            onChange={onChange}
            placeholder="Title"
          />
```

## Screenshots
![Screen Shot 2022-06-06 at 1 15 50 AM](https://user-images.githubusercontent.com/42456594/172105842-2e4c8322-ee91-4b6d-a396-c49bd26edb4f.png)

**Comment by igor-giusti** [comment]
Text Blocks are created by just typing into the editor. That's why it's not displayed in plugins menu.

Image and Video plugins are the default plugins when no `plugins` props is passed to `<MegadraftEditor />` component and the screenshot shows they are correctly rendered.
