### ISSUE TITLE
Title accepts Bold style

### ISSUE THREAD

**Issue by ArxdSilva** [globocom/megadraft#39]
As a title is already bold, It should be blocked on Toolbar to add as style, to prevent adding useless info to json file.

**Comment by vierno** [comment]
Related issue: https://github.com/facebook/draft-js/issues/486

**Comment by ricobl** [comment]
I'm not sure this is a problem, bold is a way to represent the `strong` tag that has a semantic meaning.

But having control over the possible styles as the issue suggests is good. In case the issue gets solved, `Megadraft` should be able to detect possible styles for a selection, enabling or disabling toolbar buttons.
