### ISSUE TITLE
Update Project Latest React

### ISSUE THREAD

**Issue by lucasferreiralimax** [globocom/megadraft#391]
# Update Project Latest React

Update react for last version 18 and up news compatibility

## Description

Re-write old structure with new structure for [React v18](https://reactjs.org/versions/)

## Motivation

Update project for new compatibility and news features from React latest

**Comment by meerhamzadev** [comment]
So In this issue, we are supposed to update react 17 to react 18 just? or are We also supposed to restructure the codebase according to the react 18?

**Comment by meerhamzadev** [comment]
Vite has some great use cases, and the instant reloads feedback is crazy. But without code splitting enabled it's a little slow compared to webpack 5 in cold starts and production builds.

**Comment by meerhamzadev** [comment]
@lucasferreiralimax Yes both tools are good and applicable in your scenario. I think its better to stay on webpack and update your project to from webpack 4 to 5.

**Comment by clebsonf** [comment]
I worked on updating the webpack at #404

**Comment by Kathuria** [comment]
Can I work on this?
