### ISSUE TITLE
Design Responsivo a página do Projeto: megadraft.io

### ISSUE THREAD

**Issue by anamariasilva** [globocom/megadraft#426]
# -- Feature --
Design Responsivo ao site https://megadraft.io/ do Projeto Megadraft

## Description
Na versão responsiva do site, é necessário o desenvolvimento front-end da versão responsiva para mobile do site Megadraft.

## Motivation
Maior usabilidade ao site do Projeto ao ser acessado em dispositivos móveis.

**Comment by marcelometal** [comment]
Olá @anamariasilva o site é responsivo, alguma parte dele não funcionou?!

**Comment by lucaoskaique** [comment]
> Olá @anamariasilva o site é responsivo, alguma parte dele não funcionou?!


Testei no polypane e quebra só em um breakpoint, o 900px acho que é tablet né?

![image](https://github.com/globocom/megadraft/assets/20323741/51bac938-fed6-4d37-9390-29abe75116c3)

**Comment by marcelometal** [comment]
Olá  @lucaoskaique , 
ainda não consegui reproduzir... O problema nesse breakpoint é essa faixa abaixo do "Let`s Rock"?

Alem de usar o meu navegador  (chrome, chromium e firefox) também tentei usar  http://responsivetesttool.com/

Vou testar e entender o que o `polypane` faz...

**Comment by lucaoskaique** [comment]
Eu só recebi o email do hackatoberfest da globo e vim ver as issues, dai só abri o polypane para ver mesmo se tinha problema, frontend css não é muito minha praia kkk.

**Comment by anamariasilva** [comment]
A imagem principal da página está responsiva, mas o texto da página exibe a versão para web ao ser acessada em dispositivos móveis.

**Comment by lucianapepelucio** [comment]
This was completed in #435
