### ISSUE TITLE
Cannot read property 'getCurrentContent' of null

### ISSUE THREAD

**Issue by gstoyanov90** [globocom/megadraft#59]
I'm not advanced in react , just trying to build myself a blog and found that megadraft will do amazing job for me. I just tried to implement it following the Overview section, but it returns 

> Cannot read property 'getCurrentContent' of null
> 

Not sure if this is bug or not :/
I'm using following dependencies: Webpack, React, React Router, React DOM and following code:
        `
         export default React.createClass({ 

	getInitialState: function () {
	    return {
	    	editorState: null,
	    }
  	},
	onChange(editorState) {
		this.setState({editorState: editorState});
	},

  	render() {
	    return (
                <Megadraft
                    editorState={this.state.editorState}
                    onChange={this.onChange}/>
	    );
  	}
    });`

**Comment by ricobl** [comment]
Hi @gstoyanov90!

It is great to know that you liked `Megadraft`.

Looks like our sample code is wrong, we'll try to fix it.

In the mean time, you could try using the `editorStateFromRaw` function, it will should work with `null` or a raw json state object.

https://github.com/globocom/megadraft/blob/master/src/utils.js#L24

Here is how it is used on our website:

https://github.com/globocom/megadraft/blob/master/website/components/example.js

But note that your `import` should be different:

```
import {editorStateToJSON, editorStateFromRaw} from "megadraft/lib/utils";
```

Please let us know if this works for you.

**Comment by gstoyanov90** [comment]
Now everything is working, also I've just found a way to "fix" (probably it's workaround) of original overview example - just importing EditorState from draftjs + editorState: EditorState.createEmpty().
Sadly I just get that : https://s32.postimg.org/nx8d3z285/megadraft.jpg
Buttons are working great, think that there is something with css styles (that toolbar elements shouldn't be displayed like this and there's no place to add text), I'll try to find and will be great if you have idea how to fix it :) 
Thanks for the support!

**Comment by ricobl** [comment]
Great! You're welcome!

You should probably include the `dist/css/megadraft.css` stylesheet in your page.

We'll try to improve our docs to point that out.

**Comment by gstoyanov90** [comment]
It's ok now. I really like it, when I finish this little blog, I'll try to support you guys :)

**Comment by ricobl** [comment]
That's great @gstoyanov90! I'm glad you liked it.

Thanks! We could use some support! :)
