### ISSUE TITLE
adding other commonly features

### ISSUE THREAD

**Issue by imasood** [globocom/megadraft#61]
hi guys,
the toolbar of megadraft isn't very complete, i think it should be added other commonly features like underline, headings, ...
thanks

**Comment by ricobl** [comment]
Hi @imasood!

We're lacking documentation but the toolbar is customizable, here are the default actions:
https://github.com/globocom/megadraft/blob/master/src/actions/default.js

You could pass your own actions. It's untested but should look something like this:

```
class App extends React.Component {
  render() {
    const actions = [
      {type: "inline", label: "U", style: "UNDERLINE", icon: yourIcons.UnderlineIcon}
    ];
    return (
      <Megadraft
        actions={actions}
        editorState={this.state.editorState}
        onChange={this.onChange}/>
    )
  }
}
```

Does that work for you?

**Comment by imasood** [comment]
it's seems work but there's a problem in `icon`.
i'm not so familiar with `megadraft` structure and the document is so poor.
what should i do for the `icon`?
thanks

**Comment by ricobl** [comment]
I'm sorry it's not clear, we really have to improve our docs. It's great to have people like you pointing out topics we should improve.

The icons are React components, we usually adapt SVGs from [Google's Material Design Icons][material] and convert them to JSX. Here is the bold icon as an example:
https://github.com/globocom/megadraft/blob/master/src/icons/bold.js

You can import built-in icons like this:

```js
import {MegadraftIcons} from "megadraft";
# Bold Icon:
# MegadraftIcons.BoldIcon
```

Please let me know if this works for you.

[material]: https://design.google.com/icons/

**Comment by imasood** [comment]
I used to another way to solve this problem.
Any way, as soon as i have enough time it's my pleasure to improve megadraft docs.

**Comment by ricobl** [comment]
Great @imasood! Your help would be awesome!
