### ISSUE TITLE
scss is not included in the distrubution

### ISSUE THREAD

**Issue by episodeyang** [globocom/megadraft#63]
Hi there~~ Thanks for this fantastic editor!

It looks like the scss is not included in the distribution.

Some of the partials might be useful if I want to cherry pick only one part of the style.

I could also just use the css though.

Ge

**Comment by ricobl** [comment]
Hi @episodeyang!

That's a great idea! We'll try to fix this and generate a new release.

Thanks for the feedback.

**Comment by ricobl** [comment]
Hey @episodeyang!

There's a new release `0.1.10` that includes Sass files.

I hope it helps. We would love to see the result of your customization and hear about your overall experience with `Megadraft`.
