### ISSUE TITLE
Evaluate migration to React 0.15.3 and usage of React.PureComponent

### ISSUE THREAD

**Issue by ricobl** [globocom/megadraft#64]
Performance could be improved on most components using `PureComponent`:

https://github.com/facebook/react/pull/7195

**Comment by andrewb** [comment]
@ricobl would you be interested in a PR to update to React 15.6, migrate to the prop-types library, etc?

**Comment by petry** [comment]
Sure @andrewb ! it'll be a great addition to Megadraft! Feel free to open this PR to us!

**Comment by ricobl** [comment]
Closing this issue as it's really outdated.
