### ISSUE TITLE
Electron propmt function in media elements

### ISSUE THREAD

**Issue by imasood** [globocom/megadraft#65]
Hi Guys,
I'm writing an @electron app but it doesn't let to run `prompt` js function and for this reason actually media element like video or photo they're going to useless.
Anybody have idea to solve this problem?
Thanks

**Comment by vierno** [comment]
Hello @imasood, 

We have no solution for this with the default plugins atm. One solution would be using an html input, in a prompt-like html modal, if you want to contribute to Megadraft, we could use this =)

If you wish, you could write a modified version of the plugins and use with the editor, with another action when the user clicks the button (internally we open our media browser this way).

**Comment by vierno** [comment]
This guy does something like that:
https://github.com/coderaiser/smalltalk

**Comment by ricobl** [comment]
Hey @imasood!

I'm closing this issue as it's not a related to Megadraft itself ok?

Please feel free to ask for help if you need!
