### ISSUE TITLE
image functionality not working

### ISSUE THREAD

**Issue by Jbarget** [globocom/megadraft#70]
heya!

great module you got here!
On the demo site a few of the functions to adjust images don't seem to work for me:
- crop
- sizing
- the 'edit' button

I'm on chrome 52 if that helps...

![screen shot 2016-09-06 at 17 46 16](https://cloud.githubusercontent.com/assets/11725595/18282747/6413f266-745a-11e6-97bd-627ed35af4db.png)

**Comment by ricobl** [comment]
Hi @Jbarget!

Thanks for reporting.

The sizing dropdown doesn't resizes the image on the interface, it just changes the `display` option on the block metadata. You can check the serialized state on the "content json" tab of our demo:

http://globocom.github.io/megadraft/

As for the buttons, they are intended to work as an example of how to use buttons on a component, maybe we shouldn't have them on the built-in image component.

Looks like there's nothing wrong with your environment.

I've opened another issue for this and I'll close this one ok?

Please let us know if you find something else.

**Comment by Jbarget** [comment]
sure thing! thanks :)

**Comment by ricobl** [comment]
You're welcome! :)
