### ISSUE TITLE
insertDataBlock is not possible to use

### ISSUE THREAD

**Issue by AndySeg** [globocom/megadraft#73]
When I create import like: import {DraftJS, insertDataBlock} from "megadraft"; the insertDataBlock is not possible to use because it was not possible to use insertDataBlock in code and it was null.

**Comment by ricobl** [comment]
Hi @AndySeg, do you have this code available anywhere? Are you using the latest version of Megadraft (0.2.0)?

We've just released a new version of the `generator-megadraft-plugin`, also 0.2.0. It may help if you're creating a plugin.

**Comment by ricobl** [comment]
@AndySeg: I'll close this issue ok?

Feel free to re-open if you need...
