### ISSUE TITLE
key value is still null in function get(key) in DraftEntity.js

### ISSUE THREAD

**Issue by AndySeg** [globocom/megadraft#74]
I created code like is described in http://globocom.github.io/megadraft/#/docs/plugins?_k=hbjwzp and it is not possible to created new video element because I have still problem: invariant.js:38 Uncaught Invariant Violation: Unknown DraftEntity key. and in code DraftEntity.js on line 68 is key value null.

**Comment by ricobl** [comment]
Hey @AndySeg, thanks for reporting!

Looks like our Yeoman generator is outdated, we'll post back here after it is updated.

**Comment by ricobl** [comment]
Hi @AndySeg, there's a new version of the `generator-megadraft-plugin`. You can update it running:

```
npm install -g generator-megadraft-plugin@latest
```

Please let us know if this works for you or if you.

**Comment by ricobl** [comment]
@AndySeg: I'll close this issue ok?

Feel free to re-open if you need...
