### ISSUE TITLE
ability to add 'alt text' to an image 

### ISSUE THREAD

**Issue by Jbarget** [globocom/megadraft#75]
It would be good to have a field as well as 'caption' and 'rights holder' for 'alt text' to help  accessibility

thoughts?
would you accept a PR?

**Comment by ricobl** [comment]
Can't you use a combination o `caption` and `rightsHolder` to render the `alt` text? That's the way we use.

How do you feel about creating a custom plugin? It's easy using the plugin generator: https://github.com/globocom/generator-megadraft-plugin

**Comment by Jbarget** [comment]
Unfortunately I wouldnt be able to use a combination of the `caption` and `rightsHolder`, the project im working on is for journalists and the caption can be quite different from the alt text

from the bbc website:
![screen shot 2016-09-15 at 14 32 00](https://cloud.githubusercontent.com/assets/11725595/18551642/31fee602-7b51-11e6-8d53-a36ab28d5a6a.png)

**Comment by ricobl** [comment]
I see, in that case you'll need the `alt` field.

How do you feel about creating your own image plugin?

**Comment by Jbarget** [comment]
do you have an example plugin i could use as a reference? Im happy to give it a go but not too sure how to go about it

**Comment by ricobl** [comment]
We used the generator to create the [megadraft-related-articles-plugin](https://github.com/globocom/megadraft-related-articles-plugin). You can use it as reference.

But I strongly recommend using the generator, after a few commands you'll end up with a basic  plugin running on a local gulp server with watch tasks for JS and SCSS. Here is the docs about the plugin system:

http://globocom.github.io/megadraft/#/docs/plugins

**Comment by Jbarget** [comment]
perfect thank you!

**Comment by ricobl** [comment]
You're welcome @Jbarget! I'm closing the issue ok?

BTW, you can also reach us on the [#megadraft](https://draftjs.slack.com/messages/megadraft/) channel on DraftJS' Slack page.

**Comment by Jbarget** [comment]
all good!
