### ISSUE TITLE
Responsive client for megadraft

### ISSUE THREAD

**Issue by amorimgustavo** [globocom/megadraft#77]
Visual reference

![screenshot_20160927-185440](https://cloud.githubusercontent.com/assets/5922117/18893405/2cd16370-84e4-11e6-880d-c8ed840c963f.png)

**Comment by ricobl** [comment]
Hey @amorimgustavo, can you explain a little bit more?

Is this an issue? A feature request?

**Comment by ricobl** [comment]
@amorimgustavo: I'm closing the issue ok? Feel free to reopen if you need.
