### ISSUE TITLE
link youtube video

### ISSUE THREAD

**Issue by johannchen** [globocom/megadraft#81]
The youtube video does not show up after I inserted the link of the youtube video. Is it a bug?

**Comment by marcelometal** [comment]
Hi @johannchen,

It is not a bug, this component only accepts real video link (mp4, ogv, etc), like:
http://techslides.com/demos/sample-videos/small.ogv

**Comment by johannchen** [comment]
Thanks for the explanation.  Will megadraft plan to link youtube video directly to the editor?

**Comment by marcelometal** [comment]
Not now... But you can create it, there's a [Megadraft Yeoman generator](https://github.com/globocom/generator-megadraft-plugin)
