### ISSUE TITLE
Hiding sidebar when selectedBlock is not empty

### ISSUE THREAD

**Issue by SeverS** [globocom/megadraft#85]
Hello,

I think sidebar should be hidden when the selected block has text.
I can create a PR with this feature if it`s ok.

Thanks

**Comment by ricobl** [comment]
Hello @SeverS! Thanks for the suggestion!

Please help me understand, what is the motivation behind your idea? A cleaner look or something else?

If I got it right, the user would have to create an empty line before inserting a new block from the sidebar. Is that correct? Is it worthy to add this extra step?

**Comment by SeverS** [comment]
Hello @ricobl,

I have 2 main reasons for this:
1. You can`t actually insert a picture at the caret position (only if caret is at the beginning of a new line)
2. If you would prefer to open the sidebar horizontally (like in the attached image) you will end up messing with the design :)

![sidebar-over-text](https://cloud.githubusercontent.com/assets/5903809/19565443/883eb4e8-96ef-11e6-9a7c-aeb194b597bf.PNG)

**Comment by ricobl** [comment]
Hey @SeverS!

About your reasons:

1. you're right, you can't insert a picture at the caret position. The idea is that you can float an image left or right on the actual website using a separate image block.
2. maybe you could create a PR adding the ability to pass a different component for the sidebar, and then you can write your own. This way both behaviors would be possible. Something like this:

```js
function mySidebarFn(???) {
  return MySidebar(???);
}
<MegadraftEditor sidebarComponentFn={mySidebarFn} />
```

**Comment by SeverS** [comment]
@ricobl Cool, that`s better actually.
I`ll create a PR over the weekend.
Thanks :D

**Comment by ricobl** [comment]
Awesome @SeverS! That would be great.

I'm closing the issue for now ok?
