### ISSUE TITLE
Using a rich text editor on mobile.

### ISSUE THREAD

**Issue by magician11** [globocom/megadraft#88]
We're looking to add a draftjs implementation to our web app. We notice the native toolbar on devices (with copy, paste) really gets in the way a lot. Including with your implementation here.

![realios_iphone_6s_plus](https://cloud.githubusercontent.com/assets/3735849/19728304/1a225a50-9bbd-11e6-888b-02b05f0b9396.jpg)

Thoughts? Experiences?

**Comment by ricobl** [comment]
Hey @magician11! We haven't put much effort into making Megadraft work on mobile devices.

Even if we fix the toolbar, the overall experience needs to be revised to provide a good experience on a small screen.

Do you have any ideas?

**Comment by magician11** [comment]
Well the first obvious idea was to just use a fixed toolbar. But even that can be an issue...

![screenshot_20161026-200824](https://cloud.githubusercontent.com/assets/3735849/19729133/18648776-9bc0-11e6-9380-a306137d6060.png)

I had a look at medium.com and [they require users to use the desktop or their native app](https://help.medium.com/hc/en-us/articles/216408258-How-do-I-write-). With a native app it looks like you can modify the native toolbar and keyboard to add rich text options.

So overall, no clear ideas really. I had a brief chat on the draftjs slack channel, and a snippet of that conversation was...

![screen shot 2016-10-26 at 8 48 46 pm](https://cloud.githubusercontent.com/assets/3735849/19729213/72586270-9bc0-11e6-9d7c-17a40516be3d.png)

I had a look at Google Docs on my phone (the native app), and the markup options are much more limited (there basically are not any) than the desktop view.

Sort of seems not using rich text on mobile devices is the current best practice.

**Comment by ricobl** [comment]
Looks like you did a good research, thanks for sharing!

I saw the conversation on Slack, we have a `#megadraft` channel there...

We don't have plans to work on a mobile solution in the short term, but it could happen in the future.

For now, I'm closing the issue ok? Feel free to comment!

**Comment by magician11** [comment]
@ricobl We're thinking of still using the tooltip editor for desktop, but disabling it on mobile. Is there a way to disable this editor via some prop?

We could then still view the marked up content on small devices, but only use standard/native editing controls when on small screens. I'm thinking the logic to dictate when the tooltip editor is disabled will be handled by the parent container app.

**Comment by ricobl** [comment]
Hey @magician11!

Currently there's no way of doing that, but I believe it wouldn't be hard to implement.

A [recent PR](https://github.com/globocom/megadraft/pull/87) introduced the ability to use a custom sidebar component, I believe that a similar approach for the `Toolbar` would be neat.

How do you feel about giving it a try?

**Comment by magician11** [comment]
Hi @ricobl 

Wouldn't it just be a matter of changing [this line](https://github.com/globocom/megadraft/blob/master/src/components/Toolbar.js#L155) to something like..

```
  render() {
    if(this.props.readOnly || this.props.toolbarIsDisabled) {
      return null;
    }
```

?

**Comment by ricobl** [comment]
The flag seems to solve the issue at hand, but having something like a renderer function would give us a lot more flexibility.
