### ISSUE TITLE
can't remove empty line between two plugins

### ISSUE THREAD

**Issue by macrozone** [globocom/megadraft#92]
ways to reproduce:

- goto http://globocom.github.io/megadraft/
- add another image right after the first

you will see an empty line between the two plugins. setting the cursor there and hitting backspace will remove the previous plugin. You can't get rid of this line without deleting the inserted plugin

**Comment by vierno** [comment]
Hello,

We can't get rid of this empty line right now, if it's deleted, it would become impossible to insert anything between the two plugins. 
We could remove it once we have drag and drop available.

**Comment by macrozone** [comment]
Do you have any idea for a workaround? Problem seems that the cursor "jumps" over the component. Is it possible to somehow force it exactly before the plugin?

**Comment by vierno** [comment]
I think we have no good workaround atm.
We should be able to implement a "focused" state in the atomic blocks (#27), so by pressing enter we could insert a line before/after it and the cursor would not be jumping anymore, but it seems that it's not a simple implementation.
