### ISSUE TITLE
Exporting to HTML

### ISSUE THREAD

**Issue by madshargreave** [globocom/megadraft#93]
Hi

Has anyone had success with exporting the generated JSON to HTML?

I've tried the draft-js-import-html project, but it fails with the error

Uncaught Error: Unknown DraftEntity key.

**Comment by vierno** [comment]
Hi,

We have a Python based backend, we are using this project to render some of our html: https://github.com/springload/draftjs_exporter

Never tried draft-js-import-html, though.

**Comment by ricobl** [comment]
Hey @madshargreave!

A little bit late but you can try to find tools here:

https://github.com/nikgraf/awesome-draft-js#common-utilities

I'm closing the issue ok? Feel free to comment!

**Comment by kunokdev** [comment]
Are those tools compatible wtih this lib? It seems editorState object is not same here as in draftjs? All examples and libraries fail with error
