### ISSUE TITLE
Editor will disable "readOnly" when a plugin receives "focus"

### ISSUE THREAD

**Issue by macrozone** [globocom/megadraft#97]
If the editor has `readOnly=true`, it can switch to `readOnly=false` when a plugin receives focus and you click afterwards somewhere in the editor.

E.g. if a plugin has a button or a link you can tab into the plugin to this button and then click on normal editor text.

I think if `<MegadraftEditor />` has `readOnly=true`, it should never set its state.readOnly to false.

what you think?

**Comment by cameacke** [comment]
+1, this is a big problem for me, might be a deal breaker for me using this tool as much as I like it. 

I'm going to experiment with specialized "readonly plugins" which are going to be versions of the normal plugins that have hardcoded readonly fields.

**Comment by cameacke** [comment]
This probably has something to do with the code here:https://github.com/globocom/megadraft/blob/master/src/components/MediaWrapper.js
 
Is onBlur not being invoked properly?

**Comment by ricobl** [comment]
Thanks for the fix @cameackeSEL! Great job!

It's released under the `0.4.18` version.

We're lacking docs about `blockComponent` props, I've created an issue for this: #137.
