### ISSUE TITLE
Click on Link in Toolbar should allow to update the url

### ISSUE THREAD

**Issue by macrozone** [globocom/megadraft#98]
If you have selected a link and click on the link-button (or any custom entity-input), it will remove the link/entity.

It would be more flexible if you could edit the entity when clicking on the button and e.g. change the url. There, we could have a "remove" button that removes the entity.

I'll do eventually a PR for that, if there is no objection.

**Comment by ricobl** [comment]
Hey @macrozone! There's no objection at all.

We have a slightly different experience planned for removing / editing entities, somewhat similar to Google Drive. I'll post the layout here as soon as I get it from our designer.

**Comment by macrozone** [comment]
Hi @ricobl , 

Can you check if the api is ok for you that i created in the PR? 
Basically the entity-input, e.g LinkInput receives a function to remove the entity. This is easy to implement with custom entities and also with custom toolbar. Of cource you can also call removeEntity from the toolbar itself, e.g. if you want to display two buttons, when a certain entity is active on the current selection.

**Comment by ricobl** [comment]
The api is looking good to me @macrozone!

Here is the layout for the link editing flow:

![link-editing-flow](https://cloud.githubusercontent.com/assets/134148/20349082/e74be13a-abef-11e6-81a5-ec855775cd80.png)

And the possible states explained:

1. text selection shows toolbar and the user can click the link button to show the URL input
2. the user can enter the URL or cancel either by pressing ESC or clicking the "X" button
3. after entering the URL, the user can press ENTER to apply the link
4. the link is applied
5. when the cursor is on the link, a popover is shown with a clickable link, an edit button and a remove link button
6. the toolbar on edit mode

**Comment by marcelometal** [comment]
feature implemented, so I'm closing this issue.
